name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=src" >> $GITHUB_ENV

    - name: Debug PYTHONPATH
      run: echo "PYTHONPATH is $PYTHONPATH"

    - name: List directory
      run: |
        echo "Listing the root directory:"
        ls -al
        echo "Listing the src directory:"
        ls -al src
        echo "Listing the tests directory:"
        ls -al src/tests

    - name: List installed packages
      run: pip list

    - name: Print Python version
      run: python --version

    - name: Lint with flake8
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Pytest
      run: |
        echo "Running Pytest:"
        pytest --maxfail=1 --disable-warnings -v
